#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Oct 20 19:59:06 2017

@author: ishxiao
~Email~: me@ishxiao.com

"""

from aps import hardware_info

def test_about():
    try:
        hardware_info()
    except:
        assert False
    assert True